解决了Django2.2 连接MySQL的各种报错！
1. 首先在settings中配置数据库为mysql
2. 在同目录下的init中 添加
import pymysql
pymysql.install_as_MySQLdb()
3. 这个时候应该会报错
    django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.

4. 找到报错的文件，将
if version < (1, 3, 13):
    raise ImproperlyConfigured('mysqlclient 1.3.13 or newer 注释掉

5. 这个时候不出意外还会报错
    AttributeError: 'str' object has no attribute 'decode'

6. 找到报错的py文件，将decode改为encode
            if query is not None:
            query = query.encode(errors='replace')

7. 执行python manage.py migrate